version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    ports:
      - "8181:8080"
    depends_on:
      - mysql
    command:
      - start-dev
    networks:
      - keycloak-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  mysql-data:
