services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container_inventory
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: user_inventory
      MYSQL_PASSWORD: password_inventory
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_EXTRA_FLAGS: "--innodb-force-recovery=1"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
